sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
node_js:
  - iojs
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g grunt-cli
before_script:
  - npm prune
after_success:
  - grunt
  - npm run semantic-release
